global:
  scrape_interval:     60s
  evaluation_interval: 60s
 
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: mysqld
    static_configs:
      - targets: ['mysqlexporter:9104']
      
  - job_name: 'node'
    static_configs:
      - targets: ['nodeexporter:9100']